pip install accelerate -i https://pypi.tuna.tsinghua.edu.cn/simple/ 
pip install scikit-learn -i https://pypi.tuna.tsinghua.edu.cn/simple/ 
pip install seaborn -i https://pypi.tuna.tsinghua.edu.cn/simple/ 
pip install sentencepiece -i https://pypi.tuna.tsinghua.edu.cn/simple/ 
pip install wandb -i https://pypi.tuna.tsinghua.edu.cn/simple/ 
pip install trl -i https://pypi.tuna.tsinghua.edu.cn/simple/ 
pip install flash_attn -i https://pypi.tuna.tsinghua.edu.cn/simple/ 
pip install deepspeed -i https://pypi.tuna.tsinghua.edu.cn/simple/ 
pip install peft -i https://pypi.tuna.tsinghua.edu.cn/simple/ 
pip install bitsandbytes -i https://pypi.tuna.tsinghua.edu.cn/simple/ 